version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-ecr: circleci/aws-ecr@4.0.1
executors:
  build_container:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/mysql:5.7
        command: mysqld --lower_case_table_names=1
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
        environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m
        entrypoint: >
          bash -c "elasticsearch-plugin install analysis-kuromoji && docker-entrypoint.sh"
      - image: localstack/localstack
        environment:
          - SERVICES=sqs:9324
    environment:
      - CGO_ENABLED: 0
      - GOOS: "linux"
      - GOARCH: "amd64"
      - MYSQL_USER: "root"
      - MYSQL_PASSWORD: ""
      - MYSQL_ENDPOINT: "127.0.0.1:3306"
      - MYSQL_DB_NAME: "bizv4"
      - MYSQL_MESSAGE_USER: "root"
      - MYSQL_MESSAGE_PASSWORD: ""
      - MYSQL_MESSAGE_ENDPOINT: "127.0.0.1:3306"
      - MYSQL_MESSAGE_DB_NAME: "bizmg"
commands:
  build:
    parameters:
      file_path:
        type: string
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Execute kotlin build
          command: |
            cd << parameters.file_path >>
            # TODO
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.file_path >>/main // TODO
