version: '3'
services:
  # TODO: 事前に ./gradlew build -x test が必要な状態を解決
  apiserver:
    build: apiserver
    container_name: apiserver
    volumes:
      - ./../:/spa-cucumber
    working_dir: /spa-cucumber
    ports:
      - 8080:8080
  frontserver:
    build: frontserver
    container_name: frontserver
    volumes:
      - ./../frontend-app:/spa-cucumber/frontend-app
    working_dir: /spa-cucumber/frontend-app
    ports:
      - 4200:4200
  chrome:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium_chrome
    ports:
      - 4444:4444
      - 5901:5900
