version: '3'
services:
  apiserver:
    build: apiserver
    container_name: apiserver
    volumes:
      - ./../api-server:/spa-cucumber/api-server
    working_dir: /spa-cucumber/api-server
  frontserver:
    build: frontserver
    container_name: frontserver
    volumes:
      - ./../frontend-app:/spa-cucumber/frontend-app
    working_dir: /spa-cucumber/frontend-app
  chrome:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium_chrome
    ports:
      - 4444:4444
      - 5901:5900
